### ISSUE TITLE
Test suite fails with Mojolicious 6.03 and later

### ISSUE THREAD

**Issue by eserte** [kberov/Ado-Plugin-Vest#1]
See
* http://matrix.cpantesters.org/?dist=Ado-Plugin-Vest%200.09
* http://analysis.cpantesters.org/reports_by_field?distv=Ado-Plugin-Vest-0.09;field=mod%3AMojolicious

**Comment by kberov** [comment]
Thanks @eserte!

**Comment by kberov** [comment]
Fixed with commit 8d92f4fd 
The problem was due to change of API in Ado and not in Mojolicious.
Fixed:http://www.cpantesters.org/distro/A/Ado-Plugin-Vest.html#Ado-Plugin-Vest-0.10
Thanks again!
